parameters:
    liuggio_stats_d_client.service.class: Liuggio\StatsdClient\StatsdClient
    liuggio_stats_d_client.entity.class: Liuggio\StatsdClient\Entity\StatsdData
    liuggio_stats_d_client.factory.class: Liuggio\StatsdClient\Factory\StatsdDataFactory
    liuggio_stats_d_client.sender.debug.class: Liuggio\StatsdClient\Sender\EchoSender
    liuggio_stats_d_client.collector.service.class: Liuggio\StatsDClientBundle\Service\StatsDCollectorService
    liuggio_stats_d_client.collector.listener.class: Liuggio\StatsDClientBundle\Listener\StatsDCollectorListener
    liuggio_stats_d_client.collector.dbal.class: Liuggio\StatsDClientBundle\StatsCollector\DbalStatsCollector
    liuggio_stats_d.sender.class: Liuggio\StatsdClient\Service\StatsdService

# monolog handler
    liuggio_stats_d_client.monolog_handler.class: Liuggio\StatsdClient\Monolog\Handler\StatsDHandler

services:
# statsd-php-client
    liuggio_stats_d_client.factory:
        class: %liuggio_stats_d_client.factory.class%
        arguments: [%liuggio_stats_d_client.entity.class%]

    liuggio_stats_d_client.sender.service:
        class: %liuggio_stats_d_client.sender.class%
        arguments: [%liuggio_stats_d_client.connection.host%, %liuggio_stats_d_client.connection.port%, %liuggio_stats_d_client.connection.protocol%]

    liuggio_stats_d_client.service:
        class: %liuggio_stats_d_client.service.class%
        arguments: ['@liuggio_stats_d_client.sender.service', %liuggio_stats_d_client.connection.reduce_packet%, %liuggio_stats_d_client.connection.fail_silently%]

# collector service
    liuggio_stats_d_client.collector.service:
        class: %liuggio_stats_d_client.collector.service.class%
        arguments: ['@liuggio_stats_d_client.service']

# simplified service
    liuggio_stats_d.service:
        class: %liuggio_stats_d.sender.class%
        arguments: ['@liuggio_stats_d_client.service', '@liuggio_stats_d_client.factory']

    statsd:
         alias: liuggio_stats_d.service
