language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.3.3

before_install:
  - composer self-update

install:
  - composer install --dev

script: 
  - phpunit

notifications:
  email:
    - liuggio@gmail.com
